version: '3.9'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - VITE_APP_API_URL=http://localhost:3001
      - VITE_APP_PORT=3000
      - VITE_GOOGLE_MAPS_API_KEY=AIzaSyCD0AN71KJxlxZRi30prcsXKbmGP0NV37s
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: backend
    build: ./backend
    working_dir: /backend
    ports:
      - "3001:3001"
    command: dev
    volumes:
      - ./backend:/backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=secret
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_NAME=slztur
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    container_name: slztur_db
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=slztur
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5